import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EB_Garamond, Special_Elite } from 'next/font/google';
const serif = EB_Garamond({ subsets: ['latin'], weight: '400', variable: '--font-serif' });
const typewriter = Special_Elite({ subsets: ['latin'], weight: '400', variable: '--font-mono' });

// Add these variables to your body className


export const metadata: Metadata = {
  title: "Day2day",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${serif.variable} ${typewriter.variable} font-serif`}>
        {children}
      </body>
    </html>
  );
}
